#!/usr/bin/env python3
# Joan González Albert 2DAW
import os
import sys

branch = os.popen('git branch')
for l in branch:
    # Primero comprobaremos que el commit se hace
    # en una rama que se llame hotfix
    if (l.startswith('*') and l.split(" ")[1].startswith('hotfix')):
        file = open(sys.argv[1])
        file_content = file.read()
        # Comprobaremos que empieza por "A corregir por:"
        if (not file_content.startswith('A corregir por:')):
            print('El mensaje tiene que empezar con "A corregir por: "')
            exit(1) 
